#!/usr/bin/env bash
#
# Regenerate THIRD_PARTY_LICENSES.md from the current dependency tree.
#
# Run from the repository root before tagging a new release. The output
# satisfies Apache License 2.0 Section 4 (attribution) by enumerating every
# third-party package present in the resolved dependency tree, with its
# declared license and source repository.
#
# Note on npm workspaces:
#   This repository uses npm workspaces and hoists all packages to the
#   root node_modules/. license-checker-rseidelsohn cannot reliably split
#   production vs. dev dependencies under that layout, so the script
#   produces a single flat inventory and lists the direct production
#   dependencies of server/ manually in a "Direct Production Dependencies"
#   table read from server/package.json.
#
# Requirements:
#   - npm (already a project dependency)
#   - jq
#   - npx license-checker-rseidelsohn (downloaded on first run)
#
# Usage:
#   scripts/generate-third-party-licenses.sh
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT="${REPO_ROOT}/THIRD_PARTY_LICENSES.md"
GENERATED_DATE="$(date +%Y-%m-%d)"
TMP_ALL="$(mktemp)"
TMP_FMT="$(mktemp --suffix=.json)"
trap 'rm -f "${TMP_ALL}" "${TMP_FMT}"' EXIT

cd "${REPO_ROOT}"

cat > "${TMP_FMT}" <<'JSON'
{
  "name": "",
  "version": "",
  "licenses": "",
  "repository": "",
  "publisher": ""
}
JSON

echo "Collecting full dependency tree..."
npx --yes license-checker-rseidelsohn \
  --excludePrivatePackages \
  --customPath "${TMP_FMT}" \
  --csv \
  > "${TMP_ALL}"

TOTAL=$(($(wc -l < "${TMP_ALL}") - 1))

echo "Computing license summary..."
declare -A LICENSE_COUNT
while IFS=, read -r _module name _version licenses _repository _publisher; do
  name="${name//\"/}"
  licenses="${licenses//\"/}"
  [ -z "${name}" ] && continue
  LICENSE_COUNT["${licenses}"]=$((${LICENSE_COUNT["${licenses}"]:-0} + 1))
done < <(tail -n +2 "${TMP_ALL}")

echo "Reading direct production dependencies from server/package.json..."
DIRECT_PROD_NAMES=$(jq -r '.dependencies | keys[]' server/package.json)

echo "Building ${OUTPUT}..."

{
  echo "# Third-Party Licenses"
  echo
  echo "This file lists all third-party dependencies present in the resolved dependency tree of Zileo MCP — Thunderbird, along with their declared licenses, as required by the Apache License 2.0 Section 4 (attribution)."
  echo
  echo "> This file is regenerated by \`scripts/generate-third-party-licenses.sh\`. Run it before each release to ensure freshness."
  echo
  echo "Generated: ${GENERATED_DATE}"
  echo
  echo "## Summary"
  echo
  echo "- Total packages in dependency tree: ${TOTAL}"
  echo
  echo "### By License"
  echo
  echo "| License | Count |"
  echo "|---------|-------|"
  for lic in $(printf '%s\n' "${!LICENSE_COUNT[@]}" | sort); do
    echo "| ${lic} | ${LICENSE_COUNT[${lic}]} |"
  done
  echo
  echo "All licenses observed above are permissive open-source licenses, compatible with the project's Apache License 2.0."
  echo
  echo "---"
  echo
  echo "## Direct Production Dependencies"
  echo
  echo "These packages are declared in \`server/package.json\` as direct dependencies and are shipped in the built application. Their transitive prod deps are also shipped — see the full inventory below."
  echo
  echo "| Package | Declared In |"
  echo "|---------|-------------|"
  for dep in ${DIRECT_PROD_NAMES}; do
    echo "| \`${dep}\` | server/package.json |"
  done
  echo
  echo "---"
  echo
  echo "## Full Dependency Inventory"
  echo
  echo "All resolved packages in the dependency tree (includes both runtime and development dependencies due to the npm workspaces layout)."
  echo
  echo "| Package | Version | License | Repository |"
  echo "|---------|---------|---------|------------|"

  tail -n +2 "${TMP_ALL}" \
    | awk -F',' '{
        for (i=1;i<=NF;i++) gsub(/"/, "", $i)
        name=$2; version=$3; licenses=$4; repository=$5
        if (name == "") next
        printf("| %s | %s | %s | %s |\n", name, version, licenses, repository)
      }' \
    | sort -u

  echo
  echo "---"
  echo
  echo "## Compliance Notes"
  echo
  echo "1. **Attribution**: This file is the attribution notice required by Apache License 2.0 Section 4 (and the equivalent notice clauses of the third-party licenses listed above)."
  echo "2. **Source Code**: All dependencies are available at the repository links listed in the inventory."
  echo "3. **Modifications**: Zileo MCP — Thunderbird does not modify any third-party library source code."
  echo "4. **License Compatibility**: All third-party licenses observed in the dependency tree are permissive open-source licenses, compatible with the project's Apache License 2.0. Verify the \"By License\" summary above against this claim if a new license appears at the next regeneration."
} > "${OUTPUT}"

echo "Done. ${OUTPUT} regenerated (${TOTAL} total packages)."
